// layout.tsx
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./admin.css";
import {Toaster} from 'react-hot-toast';

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "tBase - admin",
  description: "Generated by create next app using tBase",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      url: "/tbase/tbase_fav.svg",
    },
  ],
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <div id="admin" className={`${comfortaa.variable} antialiased min-h-screen`}>
          <Toaster position="top-left"/>
          {children}
        </div>
    );
}