import type { Metadata } from "next";
import { Geist, Geist_Mono, Comfortaa } from "next/font/google"; // Added Comfortaa import
import "./admin.css";

// Initialize Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Initialize Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initialize Comfortaa
const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"], // Comfortaa supports Latin characters
  weight: ["400", "700"], // Specify the weights you want (Comfortaa supports 300, 400, 500, 600, 700)
});

export const metadata: Metadata = {
  title: "tBase - admin",
  description: "Generated by create next app using tBase",
  icons: [
    {
      rel: "icon",
      type: "image/png",
      url: "/tbase/tbase_fav.svg",
    },
  ],
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="admin" className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        {children}
    </div>
        
  );
}